/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.BaseVO;
import it.finsiel.siged.util.DateUtil;

import java.util.Date;

public class AllaccioVO extends BaseVO {
    
	private static final long serialVersionUID = 1L;

	private int protocolloId;

    private int protocolloAllacciatoId;

    private String allaccioDescrizione;

    private boolean principale;

    private Date dataRegistrazione;
    
    private String tipo;
    
    private int numeroProtocollo;
    
    
   // public String
    
	public Date getDataRegistrazione() {
		return dataRegistrazione;
	}

	public String getTipo() {
		return tipo;
	}

	public int getNumeroProtocollo() {
		return numeroProtocollo;
	}

	public void setDataRegistrazione(Date dataRegistrazione) {
		this.dataRegistrazione = dataRegistrazione;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public void setNumeroProtocollo(int numeroProtocollo) {
		this.numeroProtocollo = numeroProtocollo;
	}

	public int getProtocolloId() {
        return protocolloId;
    }

    public void setProtocolloId(int allaccioProtocolloId) {
        this.protocolloId = allaccioProtocolloId;
    }

	public String getAllaccioDescrizione() {
        return allaccioDescrizione;
    }

    public void setAllaccioDescrizione(String allaccioView) {
        this.allaccioDescrizione = allaccioView;
    }

    public boolean isPrincipale() {
        return principale;
    }

    public void setPrincipale(boolean principale) {
        this.principale = principale;
    }

    public int getProtocolloAllacciatoId() {
        return protocolloAllacciatoId;
    }

    public void setProtocolloAllacciatoId(int protocolloAllacciatoId) {
        this.protocolloAllacciatoId = protocolloAllacciatoId;
    }

	public void addDescrizioneTemplate() {
		this.allaccioDescrizione=this.numeroProtocollo+" ("+this.tipo+") del "+DateUtil.formattaData(this.dataRegistrazione.getTime());
		
	}
}