/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.VersioneVO;

import java.util.Date;

public class AssegnatarioVO extends VersioneVO {

	private static final long serialVersionUID = 1L;

	private Date dataAssegnazione;

    private Date dataOperazione;

    private char statoAssegnazione = 'S';

    private boolean competente;

    private int utenteAssegnanteId;

    private int protocolloId;

    private int ufficioAssegnatarioId;

   private int utenteAssegnatarioId;

    private int ufficioAssegnanteId;

    private int caricaAssegnatarioId;

    private int caricaAssegnanteId;

    private String msgAssegnatarioCompetente;
    
    private boolean presaVisione;

    private boolean lavorato;

    private boolean titolareProcedimento;

	
	public boolean isTitolareProcedimento() {
		return titolareProcedimento;
	}

	public void setTitolareProcedimento(boolean titolareProcedimento) {
		this.titolareProcedimento = titolareProcedimento;
	}

	public boolean isLavorato() {
		return lavorato;
	}

	public void setLavorato(boolean lavorato) {
		this.lavorato = lavorato;
	}

	public boolean isPresaVisione() {
		return presaVisione;
	}

	public void setPresaVisione(boolean presaVisione) {
		this.presaVisione = presaVisione;
	}

	public int getCaricaAssegnatarioId() {
		return caricaAssegnatarioId;
	}

	public void setCaricaAssegnatarioId(int caricaAssegnatarioId) {
		this.caricaAssegnatarioId = caricaAssegnatarioId;
	}

	public int getCaricaAssegnanteId() {
		return caricaAssegnanteId;
	}

	public void setCaricaAssegnanteId(int cariacAssegnanteId) {
		this.caricaAssegnanteId = cariacAssegnanteId;
	}
    
    public Date getDataAssegnazione() {
        return dataAssegnazione;
    }

    public void setDataAssegnazione(Date dataAssegnazione) {
        this.dataAssegnazione = dataAssegnazione;
    }

    public Date getDataOperazione() {
        return dataOperazione;
    }

    public void setDataOperazione(Date dataOperazione) {
        this.dataOperazione = dataOperazione;
    }

    public int getUtenteAssegnanteId() {
        return utenteAssegnanteId;
    }

    public void setUtenteAssegnanteId(int utenteAssegnanteId) {
        this.utenteAssegnanteId = utenteAssegnanteId;
    }

    public boolean isCompetente() {
        return competente;
    }

    public void setCompetente(boolean competente) {
        this.competente = competente;
    }

    public int getProtocolloId() {
        return protocolloId;
    }

    public void setProtocolloId(int protocolloId) {
        this.protocolloId = protocolloId;
    }

    public char getStatoAssegnazione() {
        return statoAssegnazione;
    }

    public void setStatoAssegnazione(char statoAssegnazione) {
        this.statoAssegnazione = statoAssegnazione;
    }

    public int getUfficioAssegnanteId() {
        return ufficioAssegnanteId;
    }

    public void setUfficioAssegnanteId(int ufficioAssegnanteId) {
        this.ufficioAssegnanteId = ufficioAssegnanteId;
    }

    public int getUfficioAssegnatarioId() {
        return ufficioAssegnatarioId;
    }

    public void setUfficioAssegnatarioId(int ufficioAssegnatarioId) {
        this.ufficioAssegnatarioId = ufficioAssegnatarioId;
    }

    public int getUtenteAssegnatarioId() {
        return utenteAssegnatarioId;
    }

    public void setUtenteAssegnatarioId(int utenteAssegnatarioId) {
        this.utenteAssegnatarioId = utenteAssegnatarioId;
    }

    public String getMsgAssegnatarioCompetente() {
        return msgAssegnatarioCompetente;
    }

    public void setMsgAssegnatarioCompetente(String msgAssegnatarioCompetente) {
        this.msgAssegnatarioCompetente = msgAssegnatarioCompetente;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + caricaAssegnanteId;
		result = prime * result + caricaAssegnatarioId;
		result = prime * result + (competente ? 1231 : 1237);
		result = prime
				* result
				+ ((dataAssegnazione == null) ? 0 : dataAssegnazione.hashCode());
		result = prime * result
				+ ((dataOperazione == null) ? 0 : dataOperazione.hashCode());
		result = prime * result + (lavorato ? 1231 : 1237);
		result = prime
				* result
				+ ((msgAssegnatarioCompetente == null) ? 0
						: msgAssegnatarioCompetente.hashCode());
		result = prime * result + (presaVisione ? 1231 : 1237);
		result = prime * result + protocolloId;
		result = prime * result + statoAssegnazione;
		result = prime * result + (titolareProcedimento ? 1231 : 1237);
		result = prime * result + ufficioAssegnanteId;
		result = prime * result + ufficioAssegnatarioId;
		result = prime * result + utenteAssegnanteId;
		result = prime * result + utenteAssegnatarioId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AssegnatarioVO other = (AssegnatarioVO) obj;
		if (caricaAssegnanteId != other.caricaAssegnanteId)
			return false;
		if (caricaAssegnatarioId != other.caricaAssegnatarioId)
			return false;
		if (competente != other.competente)
			return false;
		if (dataAssegnazione == null) {
			if (other.dataAssegnazione != null)
				return false;
		} else if (!dataAssegnazione.equals(other.dataAssegnazione))
			return false;
		if (dataOperazione == null) {
			if (other.dataOperazione != null)
				return false;
		} else if (!dataOperazione.equals(other.dataOperazione))
			return false;
		if (lavorato != other.lavorato)
			return false;
		if (msgAssegnatarioCompetente == null) {
			if (other.msgAssegnatarioCompetente != null)
				return false;
		} else if (!msgAssegnatarioCompetente
				.equals(other.msgAssegnatarioCompetente))
			return false;
		if (presaVisione != other.presaVisione)
			return false;
		if (protocolloId != other.protocolloId)
			return false;
		if (statoAssegnazione != other.statoAssegnazione)
			return false;
		if (titolareProcedimento != other.titolareProcedimento)
			return false;
		if (ufficioAssegnanteId != other.ufficioAssegnanteId)
			return false;
		if (ufficioAssegnatarioId != other.ufficioAssegnatarioId)
			return false;
		if (utenteAssegnanteId != other.utenteAssegnanteId)
			return false;
		if (utenteAssegnatarioId != other.utenteAssegnatarioId)
			return false;
		return true;
	}
    
    

}