/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.VersioneVO;

public class ProtocolloFascicoloVO  extends VersioneVO implements Comparable<ProtocolloFascicoloVO>{
    
	private static final long serialVersionUID = 1L;

	private int fascicoloId;

    private int protocolloId;
    
    private int ufficioProprietarioId;

    public ProtocolloFascicoloVO() {
    }

    public int getFascicoloId() {
        return fascicoloId;
    }

    public void setFascicoloId(int fascicoloId) {
        this.fascicoloId = fascicoloId;
    }

    public int getProtocolloId() {
        return protocolloId;
    }

    public void setProtocolloId(int protocolloId) {
        this.protocolloId = protocolloId;
    }

	public int getUfficioProprietarioId() {
		return ufficioProprietarioId;
	}

	public void setUfficioProprietarioId(int ufficioProprietarioId) {
		this.ufficioProprietarioId = ufficioProprietarioId;
	}
    
    public int compareTo(ProtocolloFascicoloVO r) {
		return (protocolloId > r.getProtocolloId()) ? -1
				: (protocolloId == r.getProtocolloId() ? 0 : 1);
	}
    
}