/* Generated by Together */

package it.finsiel.siged.mvc.vo.posta;

import it.finsiel.siged.mvc.vo.VersioneVO;

import java.util.Date;

public class EmailVO extends VersioneVO {
	
	private static final long serialVersionUID = 1L;

	public EmailVO() {
	}

	private String oggetto;

	private String testoMessaggio;

	private String nomeMittente;

	private String emailMittente;

	private String flagTipo;

	private Date dataRicezione;

	private Date dataSpedizione;

	private int flagEliminato;
	
    private int flagAnomalia;

	private String segnatura;

	private String contentType;

	private int aooId;

	private String messageIdHeader;

	public String getMessageIdHeader() {
		return messageIdHeader;
	}

	public void setMessageIdHeader(String messageIdHeader) {
		this.messageIdHeader = messageIdHeader;
	}

	public Date getDataSpedizione() {
		return dataSpedizione;
	}

	public void setDataSpedizione(Date dataInvio) {
		this.dataSpedizione = dataInvio;
	}

	public Date getDataRicezione() {
		return dataRicezione;
	}

	
	public void setDataRicezione(Date dataRicezione) {
		this.dataRicezione = dataRicezione;
	}

	
	public int getFlagEliminato() {
		return flagEliminato;
	}

	
	public void setFlagEliminato(int flagEliminato) {
		this.flagEliminato = flagEliminato;
	}

	public String getFlagTipo() {
		return flagTipo;
	}

	public void setFlagTipo(String flagTipo) {
		this.flagTipo = flagTipo;
	}

	public String getTestoMessaggio() {
		return testoMessaggio;
	}

	public void setTestoMessaggio(String textContent) {
		this.testoMessaggio = textContent;
	}

	public String getOggetto() {
		if (oggetto != null) {
			if (oggetto.length() > 500) 
				return oggetto.substring(1, 499);
			 else
				return oggetto;
		}
		return "";
	}

	public void setOggetto(String textSubject) {
		this.oggetto = textSubject;
	}

	public String getSegnatura() {
		return segnatura;
	}

	public void setSegnatura(String segnatura) {
		this.segnatura = segnatura;
	}

	public String getContentType() {
		return contentType;
	}
	
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}
	
	public String getEmailMittente() {
		return emailMittente;
	}

	
	public void setEmailMittente(String emailMittente) {
		this.emailMittente = emailMittente;
	}

	public String getNomeMittente() {
		if (nomeMittente != null) {
			if (nomeMittente.length() > 200) 
				return nomeMittente.substring(1, 199);
			 else
				return nomeMittente;
		}
		return "";
	}

	public void setNomeMittente(String nomeMittente) {
		this.nomeMittente = nomeMittente;
	}

	public int getAooId() {
		return aooId;
	}

	public void setAooId(int aooId) {
		this.aooId = aooId;
	}

	public int getFlagAnomalia() {
		return flagAnomalia;
	}

	public void setFlagAnomalia(int flagAnomalia) {
		this.flagAnomalia = flagAnomalia;
	}

}