/* Generated by Together */

package it.finsiel.siged.mvc.vo.log;

import it.finsiel.siged.mvc.vo.VersioneVO;
import it.finsiel.siged.util.DateUtil;

import java.util.Date;

public class EventoVO extends VersioneVO{

	private static final long serialVersionUID = 1L;

	public final static Integer NON_INVIATO = 0;

	public final static Integer INVIATO = 1;

	public final static Integer NON_NECESSARIO = 2;

	private int eventoId;

	private Date data;

	private String message;

	private int tipoLog;

	private int status;

	private int aooId;

	public EventoVO(int status, String message, int aooId,
			Date dataLog) {
		this.status = status;
		this.message = message;
		this.aooId = aooId;
		this.data = dataLog;
	}

	public EventoVO() {
	}

	public Date getData() {
		return data;
	}

	public String getDataString() {
		if (data != null)
			return DateUtil.formattaDataOra(data.getTime());
		else
			return "";
	}
	
	public String getDataStringForConservazione() {
		if (data != null)
			return DateUtil.formattaData(data.getTime());
		else
			return "";
	}

	public void setData(Date data) {
		this.data = data;
	}

	public int getEventoId() {
		return eventoId;
	}

	public void setEventoId(int eventoId) {
		this.eventoId = eventoId;
	}

	public int getTipoLog() {
		return tipoLog;
	}

	public void setTipoLog(int tipoLog) {
		this.tipoLog = tipoLog;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getAooId() {
		return aooId;
	}

	public void setAooId(int aooId) {
		this.aooId = aooId;
	}
	
	

}