/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;
import it.finsiel.siged.mvc.vo.protocollo.ProtocolloVO;

class DettaglioTipoDoc extends VersioneVO {
    public DettaglioTipoDoc() {
    }

    
    private long dettaglioTipoDocId;

    private String textValore;

    private ProtocolloVO fkProtocollo;

    
    private StrutturaTipoDocVO fkStrutturaTipoDoc;

    
    public long getDettaglioTipoDocId() {
        return dettaglioTipoDocId;
    }

    public void setDettaglioTipoDocId(long dettaglioTipoDocId) {
        this.dettaglioTipoDocId = dettaglioTipoDocId;
    }

    public ProtocolloVO getFkProtocollo() {
        return fkProtocollo;
    }

    public void setFkProtocollo(ProtocolloVO fkProtocollo) {
        this.fkProtocollo = fkProtocollo;
    }

    public StrutturaTipoDocVO getFkStrutturaTipoDoc() {
        return fkStrutturaTipoDoc;
    }

    public void setFkStrutturaTipoDoc(StrutturaTipoDocVO fkStrutturaTipoDoc) {
        this.fkStrutturaTipoDoc = fkStrutturaTipoDoc;
    }

    public String getTextValore() {
        return textValore;
    }

    public void setTextValore(String textValore) {
        this.textValore = textValore;
    }
}