/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;


public class StrutturaTipoDocVO extends VersioneVO {
    public StrutturaTipoDocVO() {
    }

    
    private long strutturaTipoDocId;   
    private String descrizioneEtichetta;
    private String statoTipoCampo;
    private long lunghezza;
    private String flagObbligatorio;
    private TipoDocumentoVO fkTipoDocumento;
    public String getDescrizioneEtichetta() {
        return descrizioneEtichetta;
    }

    public void setDescrizioneEtichetta(String descrizioneEtichetta) {
        this.descrizioneEtichetta = descrizioneEtichetta;
    }

    public TipoDocumentoVO getFkTipoDocumento() {
        return fkTipoDocumento;
    }

    public void setFkTipoDocumento(TipoDocumentoVO fkTipoDocumento) {
        this.fkTipoDocumento = fkTipoDocumento;
    }

    public String getFlagObbligatorio() {
        return flagObbligatorio;
    }

    public void setFlagObbligatorio(String flagObbligatorio) {
        this.flagObbligatorio = flagObbligatorio;
    }

    public long getLunghezza() {
        return lunghezza;
    }

    public void setLunghezza(long lunghezza) {
        this.lunghezza = lunghezza;
    }

    public String getStatoTipoCampo() {
        return statoTipoCampo;
    }

    public void setStatoTipoCampo(String statoTipoCampo) {
        this.statoTipoCampo = statoTipoCampo;
    }

    public long getStrutturaTipoDocId() {
        return strutturaTipoDocId;
    }

    public void setStrutturaTipoDocId(long strutturaTipoDocId) {
        this.strutturaTipoDocId = strutturaTipoDocId;
    }
}